language: ruby
rvm:
- 2.4.4
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
env:
  global:
  - secure: kmj2pt/MOMfVZBnWfu+zmMNM8SjzCEHg1dxkdzp7iZjZqeZiTKJJYJ+NDVjRfqiopRdGjFFRuVfuBw4D2i8VKRigncZFaWHxTzyeVAB/r3UA5j92Ftz4hSnHY1ftJGlssaqsCIUmvvteM32mhTNoJYFCt0Kt14bIqCRHP1b5BXXark1zmstCUG6VByG81ckn9UjjGNIz6iP+EwG6mnhGIUhHu1sZmxvezrAWWJCLILsR5tCkDhoMpKSNieCE3kNXaaztFJlYn3C5iYc3idcuzIbStJZlsTVyc0nGaddb+FIgWSvilU15otQAUDD6oPNioiL1VsfunmPS6UX+Qxz9eRyIcMp2G/n3FQNEMdKriAWURgSk2GFZDCueo5r0JHr2cp/RtCtR8w4Tbf+S3Jfcadp/m/mlu0zPw2nMqNlpukHqILDbnXFrjN43dlY+Src9u8A9ZxV4fhsb+jCh1HeuwraxzvmpassjHE4m9OZv64aEhulvi0cvlo+0bvPu7C6cV7MmTnEGaJ3fGvOdSMnxrf2JNjjDBbqJz5MZ3YmPKJHVJIjbLnf/h470ZJ/tzrNA1LB8LlouqEYOanOCqkx7/tdRReuciuvH6Xp89fvk0NX4+ZKzsI557PQ7hDCNJUCAvA+2hmVkI2KYT3b9MLTn8sZnsuoZLWpVQAzLYjypH9A=
  - secure: lR/VZENA2BOekO+eVEKuIr96SAhCnkP3O+CA+ajwAv7EOqF6nnvTw5aGEiCQhULoy9xgb6+inrJojNSrXNUPuAiRpIsos2lIY7eYB5nE/sIbufEj28cVZBkg78kCJ/PcMuOULNJBohJy4sxgY3Zpii3VqHW1tyczhJJDghDer1yEJypq9CMQGt6EwPdt17DTnVWK+yxg1vyjtBzEDT53DkqWeVl794Ssdx4wlRKn3xhYrr5HL6J2s95nBIhpbAPI5Y5qWZUNkhbhvpgbGoKVzcYtwgFjEGYEWxiOFQDIxgwvWQOxWIhXb/Zg4PK77Yq+gAUaDpz67S9XyS+XKci6hzm5WrbujcemJPccuPDPwDW7TECgt0QuNDQ0ynS4HM3NVCyvjUCoedBh3da5U1L073fGbbiL+lpDS5RPi4yTInijwnjbMEqji0EkQ1JHRp5U90ieIbFF5Y+8fKkjLpYynZ7cs78MizhXTkywmk9fmxDP/PTu1ZDrR3NTn/0Asz3epU61TQzgdUicdO/g1Sird2zc2NV4ucOGeXP4UCmzJDTFVIzuXeG9V8Zs3dNCMVLb+ZbsRL982QpxKSsBGxBhZybVnHiB4jj2imNFW24CYf3qKc3t+MBLp6NJHXv16AVYEvCpKTqkuhvIeEN0o2IuCjmLv+PvCMJvg0/SrAtPBkA=
