default: &default
  adapter: postgresql
  encoding: unicode
  username: admin
  password: admin
  host: localhost
  template: template0
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: flashcards_db

test:
  <<: *default
  database: flashcards_db_test

production:
  <<: *default
  database: flashcards_db
