# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c27d50b3f46bb269e046728ddbf5a2c4965dfe254545ddb45ce9db6a6d2b2b71296a93f92bdbaa705efb6c9a42c5b199febae0d83777ca2bb74c8ff1b751b463

test:
  secret_key_base: b7f4cadd389f40ad5eeb69e78aa84006027f164a7e06ed02582a56f4952cd7483e41396dadcdf66e30b38db7ce117d5a004ce79e23d63ca5acd1f449b45cc960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
